stages:
  - deploy

deploy_to_ec2:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh git
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
    - ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
  script:
    - ssh ec2-user@$EC2_HOST '
      if [ ! -d ~/productPage ]; then
      git clone git@gitlab.com:jihuns/product-page.git ~/productPage;
      else
      cd ~/productPage && git pull origin main;
      fi &&
      cd ~/productPage &&
      pm2 restart all || MONGO_URI="$MONGO_URI" pm2 start backend/server.js
      '
  only:
    - main
